<?php

namespace App;

use Cviebrock\EloquentSluggable\Sluggable;
use Illuminate\Database\Eloquent\Model;

class Technology extends Model
{
    use Sluggable;
    public function sluggable(): array
    {
		return [
			'slug' => [
				'source' => 'techno_uz'
			]
		];
    }
    public function getRouteKeyName()
    {
	    return 'slug'; // TODO: Change the autogenerated stub
    }
	public function menus()
	{
		return $this->belongsTo(Menu::class, 'menu_id');
	}
	public function parent()
	{
		return $this->belongsTo(Menu::class, 'menu_id');
	}
}
